import { Poppins } from 'next/font/google'
import '../globals.css'
import HeaderComponent from '@/components/share/header-component'
import FooterComponent from '@/components/share/footer-component'
import { i18n, type Locale } from '@/i18n.config'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}
const poppins = Poppins({
  display: 'swap',
  subsets: ['latin-ext'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins'
})

export async function generateStaticParams () {
  return i18n.locales.map(locale => ({ lang: locale }))
}

export default function RootLayout ({
  children,
  params
}: {
  children: React.ReactNode
  params: { lang: Locale }
}) {
  return (
    <html lang={params.lang} className={`${poppins.variable}`}>
      <body>
        <HeaderComponent lang={params.lang} />
        <main className='flex min-h-screen flex-col flex-1 items-center justify-between p-24'>
        {children}
        </main>
        <FooterComponent />
      </body>
    </html>
  )
}
